### ISSUE TITLE
[Suggestion] Chunk Size option

### ISSUE THREAD

**Issue by esheodinvopros** [darenliang/dsfs#2]
If the discord server has a boost level 2 or 3, the maximum file size is automatically raised to 50MB / 100MB for everyone (including bots).

Using this you can speed up uploads by 5-6 times, 10-11 times

**Comment by darenliang** [comment]
Do webhooks apply?

**Comment by esheodinvopros** [comment]
Yes, I just tested it. Webhooks also get extended file size

**Comment by darenliang** [comment]
I think this is possible but some issues might arise when a server loses its boost levels.

The current transaction format is:
```go
type Tx struct {
	Tx        int       `json:"tx"`
	Type      int       `json:"type"`
	Path      string    `json:"path"`
	FileIDs   []string  `json:"ids"`
	Checksums []string  `json:"sums"`
	Size      int64     `json:"size"`
	Mtim      time.Time `json:"mtim"`
	Ctim      time.Time `json:"ctim"`
}
```

We can add an additional Chunksize field:
```go
type Tx struct {
	Tx        int       `json:"tx"`
	Type      int       `json:"type"`
	Path      string    `json:"path"`
	FileIDs   []string  `json:"ids"`
        Chunksize int       `json:"chunk"`
	Checksums []string  `json:"sums"`
	Size      int64     `json:"size"`
	Mtim      time.Time `json:"mtim"`
	Ctim      time.Time `json:"ctim"`
}
```

It might've been a mistake to not include offsets for each FileID as using a variable chunksize would be practically impossible. What do you think about this? I think if we address the ratelimit issues from #4, we can elide this issue.

**Comment by darenliang** [comment]
I've decided to keep chunksizes constant and extend the writer queue to upload multiple chunks at once up to the message size limit.

Discord recently upped the message size limit for free users from 8MB to 25MB, so we should see faster uploads by 3 times. For nitro users the message size limit is 500MB which could see faster uploads by 62 times.

A way to automatically to determine the message size limit might be useful when dsfs starts up.
