### ISSUE TITLE
[Suggestion] User Token support

### ISSUE THREAD

**Issue by esheodinvopros** [darenliang/dsfs#3]
Nitro account as well as boosts in the discord server can also increase the max file size to 50 MB / 100 MB

Also, I'm not sure, but user accounts seem to read messages faster (again: not sure)

**Comment by darenliang** [comment]
This should be an easy change.

Would a new flag that indicates whether or not the token is for a user work?

**Comment by darenliang** [comment]
Release v0.1.14 adds user token support through the -u flag.
