### ISSUE TITLE
[Suggestion] Webhooks as a fast alternative to Bots

### ISSUE THREAD

**Issue by esheodinvopros** [darenliang/dsfs#4]
Instead of a single bot to send messages, you can use webhooks, which will upload files at a speed much faster than a single bot (depending on the number of webhooks, the more webhooks - the greater the upload speed).

**Comment by darenliang** [comment]
Using webhooks is a good idea, but I think it would be very finicky to setup.

Would you have to supply the webhook urls in the command line? Either way, this would remove the theoretical write speed limit.

**Comment by esheodinvopros** [comment]
Well, then maybe I think there should be support for configs

**Comment by darenliang** [comment]
We can support config files.

I will look into sending files via webhooks. This would be very promising as it would completely bypass our file creation limits (currently at 5 files/s) and our write speed (currently theoretically 40MB/s).

**Comment by darenliang** [comment]
I have a very quick and dirty implementation for using webhooks in the [webhook_test](https://github.com/darenliang/dsfs/tree/webhook_test) branch. From first glance, the performance still kind of sucks. Do you know what the webhook ratelimits are? Looking at the Discord API documentation, they don't give you a rough idea of what the ratelimits should be.

I'll need to clean up the overall implementation before addressing this issue because there's a lot of globals scattered around and plenty of confusing side-effects baked into the code :(

**Comment by darenliang** [comment]
There seems to be no satisfying solution to this other than using many simultaneous connections and saturating multiple ratelimit buckets.

**Comment by codytubbs** [comment]
Hi @darenliang -- I found this issue after reviewing several other projects that didn't have FUSE support.  Here's a couple of projects that are successfully supporting (multiple) webhooks:

1. [https://github.com/DisboxApp/web](https://github.com/DisboxApp/web) && [https://github.com/DisboxApp/server](https://github.com/DisboxApp/server)
powering: [https://disboxapp.github.io/web/](https://disboxapp.github.io/web/)

2. [https://github.com/forscht/ddrive](https://github.com/forscht/ddrive)
powering: [https://ddrive.forscht.dev/](https://ddrive.forscht.dev/)

**Comment by darenliang** [comment]
@codytubbs The issue isn't about whether or not webhooks can be supported, but whether or not webhooks can bypass ratelimits imposed by Discord.

Testing indicates that webhooks cannot be used to bypass or side step ratelimits.

**Comment by codytubbs** [comment]
> @codytubbs The issue isn't about whether or not webhooks can be supported, but whether or not webhooks can bypass ratelimits imposed by Discord.
> 
> Testing indicates that webhooks cannot be used to bypass or side step ratelimits.

Yep, that's partially I posted the message. Seems a lot of the projects I just went through switched to webhooks this year for better bandwidth.
